name: Exalus Home Bridge
description: "Exalus bridge add-on that allows to integrate Exalus Home via MQTT"
version: "1.1.0"
slug: exalus-home-bridge
init: false
arch:
  - amd64
  - aarch64
services:
  - mqtt:need
host_network: true
map:
  - share:rw
  - ssl:ro
options:
  controller:
    run_from_cloud: false
  mqtt:
    host: "core-mosquitto"
    port: 1883
    baseTopic: "homeassistant"
    ssl: false
    caCertificate: ""
    rejectUnauthorized: true
  general:
    logLevel: warn
    fileLogging: false
    logFileSizeKb: 512
    logFileCount: 5
schema:
  controller:
    serial: str
    pin: str
    username: str
    password: str
    run_from_cloud: bool?
  mqtt:
    host: str
    port: int
    username: str?
    password: str?
    baseTopic: str
    ssl: bool
    caCertificate: str?
    rejectUnauthorized: bool?
  general:
    logLevel: list(none|error|warn|info|debug)
    fileLogging: bool?
    logFileSizeKb: int(64,10240)?
    logFileCount: int(1,20)?